[metadata]
name = "memory-stress"

[global]
plan = "data-transfer-benchmark"
case = "stress"
total_instances = 2
builder = "docker:go"
runner = "local:docker"

[global.run.test_params]
size      = "1GiB"
latencies = '[]'
bandwidths = '[]'
concurrency = "20"
chunk_size = "20"
links_per_level = "1024"
raw_leaves = "true"
disk_store = "true"
# memory_snapshots = "detailed"
compare_http = "false"
max_in_progress_requests = "20"
max_memory_per_peer = "16Mib"
max_memory_total = "4GiB"
use_car_stores = "true"
jaeger_collector_endpoint = "http://jaeger:14268/api/traces"
block_diagnostics = "true"

[[groups]]
id = "providers"
instances = { count = 1 }

[[groups]]
id = "requestors"
instances = { count = 1 }
